export type lang = 'en' | 'fr' | 'es' | 'jp';

export const askOllamaUi = {
    en: {
        title: "Ask Ollama (phi4)",
        place: "Place",
        days: "Days",
        hours: "Hours",
        features: "Points of interest",
        avoid: "To avoid",
        style: "Ride style",
        roundTrip: "Round trip",
        ask: "Ask",
        asking: "Asking...",
        error: "Error",
        response: "Response",
        chill: "Chill",
        normal: "Normal",
        fast: "Fast boy",
        searchCity: "Search for a city...",
        natural: "Natural",
        ai: "AI",
        form: "Form",
        exportShare: "Export/Share",
        availableItineraries: "Available Itineraries",
        exportOrShareRoute: "Export or Share Route",
        exportAsGPX: "Export as GPX",
        exportAsKML: "Export as KML",
        shareToGoogleMaps: "Share to Google Maps",
        loadingRoute: "Loading route...",
        close: "Close",
        noRouteFound: "No route found",
        shortRidePrompt: "I want to go on a short ride around my location",
        scenicMountainPrompt: "Suggest a scenic mountain loop",
        lakesForestPrompt: "Show me a route with lakes and forests",
        challengingRidePrompt: "I want a challenging ride with mountain passes",
        clickItineraryInstruction: "Click on an itinerary above to select it and view it on the map.",
        locationAccessRequired: "Location access is required for this prompt. Please enable location access in your browser settings.",
    },
    fr: {
        title: "Demander à Ollama (phi4)",
        place: "Lieu",
        days: "Jours",
        hours: "Heures",
        features: "Points d’intérêt",
        avoid: "À éviter",
        style: "Style de conduite",
        roundTrip: "Aller-retour",
        ask: "Demander",
        asking: "Recherche...",
        error: "Erreur",
        response: "Réponse",
        chill: "Détente",
        normal: "Normal",
        fast: "Rapide",
        searchCity: "Rechercher une ville...",
        natural: "Naturel",
        ai: "IA",
        form: "Formulaire",
        exportShare: "Exporter/Partager",
        availableItineraries: "Itinéraires disponibles",
        exportOrShareRoute: "Exporter ou partager l'itinéraire",
        exportAsGPX: "Exporter en GPX",
        exportAsKML: "Exporter en KML",
        shareToGoogleMaps: "Partager vers Google Maps",
        loadingRoute: "Chargement de l'itinéraire...",
        close: "Fermer",
        noRouteFound: "Aucun itinéraire trouvé",
        shortRidePrompt: "Je veux faire une courte balade autour de ma position",
        scenicMountainPrompt: "Suggère une boucle panoramique en montagne",
        lakesForestPrompt: "Montre-moi un itinéraire avec des lacs et des forêts",
        challengingRidePrompt: "Je veux un trajet difficile avec des cols de montagne",
        clickItineraryInstruction: "Cliquez sur un itinéraire ci-dessus pour le sélectionner et l'afficher sur la carte.",
        locationAccessRequired: "L'accès à la localisation est requis pour cette demande. Veuillez activer l'accès à la localisation dans les paramètres de votre navigateur.",
    },
    es: {
        title: "Preguntar a Ollama (phi4)",
        place: "Lugar",
        days: "Días",
        hours: "Horas",
        features: "Puntos de interés",
        avoid: "Evitar",
        style: "Estilo de conducción",
        roundTrip: "Ida y vuelta",
        ask: "Preguntar",
        asking: "Preguntando...",
        error: "Error",
        response: "Respuesta",
        chill: "Tranquilo",
        normal: "Normal",
        fast: "Rápido",
        searchCity: "Buscar una ciudad...",
        natural: "Natural",
        ai: "IA",
        form: "Formulario",
        exportShare: "Exportar/Compartir",
        availableItineraries: "Itinerarios disponibles",
        exportOrShareRoute: "Exportar o compartir ruta",
        exportAsGPX: "Exportar como GPX",
        exportAsKML: "Exportar como KML",
        shareToGoogleMaps: "Compartir en Google Maps",
        loadingRoute: "Cargando ruta...",
        close: "Cerrar",
        noRouteFound: "No se encontró ruta",
        shortRidePrompt: "Quiero hacer un paseo corto alrededor de mi ubicación",
        scenicMountainPrompt: "Sugiere un bucle panorámico de montaña",
        lakesForestPrompt: "Muéstrame una ruta con lagos y bosques",
        challengingRidePrompt: "Quiero un paseo desafiante con puertos de montaña",
        clickItineraryInstruction: "Haz clic en un itinerario arriba para seleccionarlo y verlo en el mapa.",
        locationAccessRequired: "Se requiere acceso a la ubicación para esta consulta. Por favor, habilite el acceso a la ubicación en la configuración de su navegador.",
    },
    jp: {
        title: "Ollama (phi4) に質問",
        place: "場所",
        days: "日数",
        hours: "時間",
        features: "見どころ",
        avoid: "避ける",
        style: "走行スタイル",
        roundTrip: "往復",
        ask: "質問する",
        asking: "質問中...",
        error: "エラー",
        response: "回答",
        chill: "のんびり",
        normal: "普通",
        fast: "速い",
        searchCity: "都市を検索...",
        natural: "ナチュラル",
        ai: "AI",
        form: "フォーム",
        exportShare: "エクスポート/共有",
        availableItineraries: "利用可能な旅程",
        exportOrShareRoute: "ルートをエクスポートまたは共有",
        exportAsGPX: "GPXとしてエクスポート",
        exportAsKML: "KMLとしてエクスポート",
        shareToGoogleMaps: "Googleマップで共有",
        loadingRoute: "ルートを読み込み中...",
        close: "閉じる",
        noRouteFound: "ルートが見つかりません",
        shortRidePrompt: "現在地周辺でショートライドをしたい",
        scenicMountainPrompt: "風景の良い山のループを提案して",
        lakesForestPrompt: "湖と森のあるルートを見せて",
        challengingRidePrompt: "山道のある挑戦的なライドをしたい",
        clickItineraryInstruction: "上の旅程をクリックして選択し、地図で表示してください。",
        locationAccessRequired: "このプロンプトには位置情報へのアクセスが必要です。ブラウザの設定で位置情報アクセスを有効にしてください。",
    },
} as const;

export const FEATURES = [
    { key: 'mountains', label: { en: 'Mountains', fr: 'Montagnes', es: 'Montañas', jp: '山' } },
    { key: 'lakes', label: { en: 'Lakes', fr: 'Lacs', es: 'Lagos', jp: '湖' } },
    { key: 'ocean', label: { en: 'Ocean', fr: 'Océan', es: 'Océano', jp: '海' } },
    { key: 'forest', label: { en: 'Forest', fr: 'Forêt', es: 'Bosque', jp: '森' } },
    { key: 'city', label: { en: 'City', fr: 'Ville', es: 'Ciudad', jp: '都市' } },
];
export const AVOID = [
    { key: 'highway', label: { en: 'Highway', fr: 'Autoroute', es: 'Autopista', jp: '高速道路' } },
    { key: 'toll', label: { en: 'Toll', fr: 'Péage', es: 'Peaje', jp: '有料道路' } },
    { key: 'ferry', label: { en: 'Ferry', fr: 'Ferry', es: 'Ferry', jp: 'フェリー' } },
    { key: 'gravel', label: { en: 'Gravel', fr: 'Gravier', es: 'Grava', jp: '砂利' } },
];
export const STYLES = [
    { key: 'chill', label: { en: askOllamaUi.en.chill, fr: askOllamaUi.fr.chill, es: askOllamaUi.es.chill, jp: askOllamaUi.jp.chill } },
    { key: 'normal', label: { en: askOllamaUi.en.normal, fr: askOllamaUi.fr.normal, es: askOllamaUi.es.normal, jp: askOllamaUi.jp.normal } },
    { key: 'fast', label: { en: askOllamaUi.en.fast, fr: askOllamaUi.fr.fast, es: askOllamaUi.es.fast, jp: askOllamaUi.jp.fast } },
];

export function t(lang: lang, key: keyof typeof askOllamaUi['en']) {
    return askOllamaUi[lang]?.[key] || askOllamaUi['en'][key];
}

export function generateGPX(waypoints: { lat: number, lon: number, name: string }[]) {
    return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="4Ride" xmlns="http://www.topografix.com/GPX/1/1">\n  <rte>\n    ${waypoints.map(wp => `\n      <rtept lat="${wp.lat}" lon="${wp.lon}">\n        <name>${wp.name}</name>\n      </rtept>`).join('')}\n  </rte>\n</gpx>`;
}

export function generateKML(waypoints: { lat: number, lon: number, name: string }[], name = 'Itinerary') {
    return `<?xml version="1.0" encoding="UTF-8"?>
  <kml xmlns="http://www.opengis.net/kml/2.2">
    <Document>
      <name>${name}</name>
      <Placemark>
        <name>${name}</name>
        <LineString>
          <tessellate>1</tessellate>
          <coordinates>
            ${waypoints.map(wp => `${wp.lon},${wp.lat},0`).join('\n          ')}
          </coordinates>
        </LineString>
      </Placemark>
    </Document>
  </kml>`;
}

export function newSessionToken() {
  return Math.random().toString(36).substring(2) + Date.now().toString(36);
}

export const communityUi = {
    en: {
        title: "Community",
        conversations: "Conversations",
        friends: "Friends",
        new: "New",
        add: "Add",
        searchConversations: "Search conversations...",
        searchFriends: "Search friends...",
        searchUsers: "Search users...",
        noConversations: "No conversations",
        noMessage: "No message",
        requestsReceived: "Received requests",
        friendsCount: "Friends",
        noFriendsFound: "No friends found",
        sendMessage: "Send message",
        typeMessage: "Type your message...",
        conversationName: "Conversation name",
        selectParticipants: "Select participants",
        searchParticipants: "Search participants...",
        createConversation: "Create conversation",
        cancel: "Cancel",
        privateConversation: "Private conversation",
        newConversation: "New conversation",
        addFriend: "Add friend",
        sendRequest: "Send request",
        close: "Close",
        accept: "Accept",
        decline: "Decline",
        block: "Block",
        cancelRequest: "Cancel request",
        delete: "Delete",
        message: "Message",
        just_now: "Just now",
        hours_ago: "hours ago",
        yesterday: "Yesterday",
        loading: "Loading...",
        errorSendMessage: "Error sending message. Please try again.",
        errorCreateConversation: "Error creating conversation. Please try again.",
        errorSelectParticipants: "Please select at least one participant",
        errorConversationName: "Name is required for group conversations",
        needFriends: "You need to have friends to create a conversation",
        selectFriend: "Select at least one friend to create a conversation",
        createNewConversation: "Create a new conversation to start",
        me: "Me",
        unknownUser: "Unknown user",
        community: "Community",
        availableFriends: "Available friends",
        search: "Search...",
        requestsSent: "Sent requests",
        noConversationsFound: "No conversations found",
        selectConversation: "Select a conversation",
        online: "Online",
        noFriendsFoundFor: "No friends found for",
    },
    fr: {
        title: "Communauté",
        conversations: "Conversations",
        friends: "Amis",
        new: "Nouvelle",
        add: "Ajouter",
        searchConversations: "Rechercher conversations...",
        searchFriends: "Rechercher amis...",
        searchUsers: "Rechercher utilisateurs...",
        noConversations: "Aucune conversation",
        noMessage: "Aucun message",
        requestsReceived: "Demandes reçues",
        friendsCount: "Amis",
        noFriendsFound: "Aucun ami trouvé",
        sendMessage: "Envoyer message",
        typeMessage: "Tapez votre message...",
        conversationName: "Nom de la conversation",
        selectParticipants: "Sélectionner participants",
        searchParticipants: "Rechercher participants...",
        createConversation: "Créer conversation",
        cancel: "Annuler",
        privateConversation: "Conversation privée",
        newConversation: "Nouvelle conversation",
        addFriend: "Ajouter ami",
        sendRequest: "Envoyer demande",
        close: "Fermer",
        accept: "Accepter",
        decline: "Refuser",
        block: "Bloquer",
        cancelRequest: "Annuler demande",
        delete: "Supprimer",
        message: "Message",
        just_now: "À l'instant",
        hours_ago: "heures",
        yesterday: "Hier",
        loading: "Chargement...",
        errorSendMessage: "Erreur lors de l'envoi du message. Veuillez réessayer.",
        errorCreateConversation: "Erreur lors de la création de la conversation. Veuillez réessayer.",
        errorSelectParticipants: "Veuillez sélectionner au moins un participant",
        errorConversationName: "Le nom est obligatoire pour les conversations de groupe",
        needFriends: "Vous devez avoir des amis pour créer une conversation",
        selectFriend: "Sélectionnez au moins un ami pour créer une conversation",
        createNewConversation: "Créez une nouvelle conversation pour commencer",
        me: "Moi",
        unknownUser: "Utilisateur inconnu",
        community: "Communauté",
        availableFriends: "Amis disponibles",
        search: "Rechercher...",
        requestsSent: "Demandes envoyées",
        noConversationsFound: "Aucune conversation trouvée",
        selectConversation: "Sélectionnez une conversation",
        online: "En ligne",
        noFriendsFoundFor: "Aucun ami trouvé pour",
    },
    es: {
        title: "Comunidad",
        conversations: "Conversaciones",
        friends: "Amigos",
        new: "Nueva",
        add: "Agregar",
        searchConversations: "Buscar conversaciones...",
        searchFriends: "Buscar amigos...",
        searchUsers: "Buscar usuarios...",
        noConversations: "Sin conversaciones",
        noMessage: "Sin mensaje",
        requestsReceived: "Solicitudes recibidas",
        friendsCount: "Amigos",
        noFriendsFound: "No se encontraron amigos",
        sendMessage: "Enviar mensaje",
        typeMessage: "Escribe tu mensaje...",
        conversationName: "Nombre de conversación",
        selectParticipants: "Seleccionar participantes",
        searchParticipants: "Buscar participantes...",
        createConversation: "Crear conversación",
        cancel: "Cancelar",
        privateConversation: "Conversación privada",
        newConversation: "Nueva conversación",
        addFriend: "Agregar amigo",
        sendRequest: "Enviar solicitud",
        close: "Cerrar",
        accept: "Aceptar",
        decline: "Rechazar",
        block: "Bloquear",
        cancelRequest: "Cancelar solicitud",
        delete: "Eliminar",
        message: "Mensaje",
        just_now: "Ahora mismo",
        hours_ago: "horas",
        yesterday: "Ayer",
        loading: "Cargando...",
        errorSendMessage: "Error al enviar mensaje. Inténtalo de nuevo.",
        errorCreateConversation: "Error al crear conversación. Inténtalo de nuevo.",
        errorSelectParticipants: "Selecciona al menos un participante",
        errorConversationName: "El nombre es obligatorio para conversaciones grupales",
        needFriends: "Necesitas tener amigos para crear una conversación",
        selectFriend: "Selecciona al menos un amigo para crear una conversación",
        createNewConversation: "Crea una nueva conversación para comenzar",
        me: "Yo",
        unknownUser: "Usuario desconocido",
        community: "Comunidad",
        availableFriends: "Amigos disponibles",
        search: "Buscar...",
        requestsSent: "Solicitudes enviadas",
        noConversationsFound: "No se encontraron conversaciones",
        selectConversation: "Selecciona una conversación",
        online: "En línea",
        noFriendsFoundFor: "No se encontraron amigos para",
    },
    jp: {
        title: "コミュニティ",
        conversations: "会話",
        friends: "友達",
        new: "新しい",
        add: "追加",
        searchConversations: "会話を検索...",
        searchFriends: "友達を検索...",
        searchUsers: "ユーザーを検索...",
        noConversations: "会話なし",
        noMessage: "メッセージなし",
        requestsReceived: "受信リクエスト",
        friendsCount: "友達",
        noFriendsFound: "友達が見つかりません",
        sendMessage: "メッセージ送信",
        typeMessage: "メッセージを入力...",
        conversationName: "会話名",
        selectParticipants: "参加者選択",
        searchParticipants: "参加者を検索...",
        createConversation: "会話作成",
        cancel: "キャンセル",
        privateConversation: "プライベート会話",
        newConversation: "新しい会話",
        addFriend: "友達追加",
        sendRequest: "リクエスト送信",
        close: "閉じる",
        accept: "承諾",
        decline: "拒否",
        block: "ブロック",
        cancelRequest: "リクエスト取消",
        delete: "削除",
        message: "メッセージ",
        just_now: "たった今",
        hours_ago: "時間前",
        yesterday: "昨日",
        loading: "読み込み中...",
        errorSendMessage: "メッセージ送信エラー。再試行してください。",
        errorCreateConversation: "会話作成エラー。再試行してください。",
        errorSelectParticipants: "少なくとも1人の参加者を選択してください",
        errorConversationName: "グループ会話には名前が必要です",
        needFriends: "会話を作成するには友達が必要です",
        selectFriend: "会話を作成するには少なくとも1人の友達を選択してください",
        createNewConversation: "開始するために新しい会話を作成してください",
        me: "私",
        unknownUser: "不明なユーザー",
        community: "コミュニティ",
        availableFriends: "利用可能な友達",
        search: "検索...",
        requestsSent: "送信されたリクエスト",
        noConversationsFound: "会話が見つかりません",
        selectConversation: "会話を選択",
        online: "オンライン",
        noFriendsFoundFor: "友達が見つかりません:",
    },
} as const;

export function tCommunity(lang: lang, key: keyof typeof communityUi['en']) {
    return communityUi[lang]?.[key] || communityUi['en'][key];
}